const GEO_ALIASES = {
  "madrid": ["Madrid", "España"],
  "barcelona": ["Barcelona", "España"],
  "valencia": ["Valencia", "España"],
  "sevilla": ["Sevilla", "España"],
  "zaragoza": ["Zaragoza", "España"],
  "bilbao": ["Bilbao", "España"],
  "paris": ["París", "Francia"],
  "parís": ["París", "Francia"],
  "marsella": ["Marsella", "Francia"],
  "lyon": ["Lyon", "Francia"],
  "londres": ["Londres", "Reino Unido"],
  "manchester": ["Manchester", "Reino Unido"],
  "birmingham": ["Birmingham", "Reino Unido"],
  "berlin": ["Berlín", "Alemania"],
  "berlín": ["Berlín", "Alemania"],
  "munich": ["Múnich", "Alemania"],
  "múnich": ["Múnich", "Alemania"],
  "roma": ["Roma", "Italia"],
  "milan": ["Milán", "Italia"],
  "milán": ["Milán", "Italia"],
  "napoles": ["Nápoles", "Italia"],
  "nápoles": ["Nápoles", "Italia"],
  "lisboa": ["Lisboa", "Portugal"],
  "oporto": ["Oporto", "Portugal"],
  "porto": ["Oporto", "Portugal"],
  "bruselas": ["Bruselas", "Bélgica"],
  "amsterdam": ["Ámsterdam", "Países Bajos"],
  "rotterdam": ["Róterdam", "Países Bajos"],
  "viena": ["Viena", "Austria"],
  "zurich": ["Zúrich", "Suiza"],
  "zúrich": ["Zúrich", "Suiza"],
  "ginebra": ["Ginebra", "Suiza"],
  "estocolmo": ["Estocolmo", "Suecia"],
  "oslo": ["Oslo", "Noruega"],
  "copenhague": ["Copenhague", "Dinamarca"],
  "helsinki": ["Helsinki", "Finlandia"],
  "dublin": ["Dublín", "Irlanda"],
  "dublín": ["Dublín", "Irlanda"],
  "varsovia": ["Varsovia", "Polonia"],
  "cracovia": ["Cracovia", "Polonia"],
  "praga": ["Praga", "Chequia"],
  "budapest": ["Budapest", "Hungría"],
  "atenas": ["Atenas", "Grecia"],
  "bucarest": ["Bucarest", "Rumanía"],
  "sofia": ["Sofía", "Bulgaria"],
  "zagreb": ["Zagreb", "Croacia"],
  "belgrado": ["Belgrado", "Serbia"],
  "moscu": ["Moscú", "Rusia"],
  "moscú": ["Moscú", "Rusia"],
  "san petersburgo": ["San Petersburgo", "Rusia"],
  "kiev": ["Kiev", "Ucrania"],
  "kyiv": ["Kiev", "Ucrania"],
  "la habana": ["La Habana", "Cuba"],
  "santiago de cuba": ["Santiago de Cuba", "Cuba"],
  "holguin": ["Holguín", "Cuba"],
  "holguín": ["Holguín", "Cuba"],
  "ciudad de mexico": ["Ciudad de México", "México"],
  "ciudad de méxico": ["Ciudad de México", "México"],
  "mexico df": ["Ciudad de México", "México"],
  "guadalajara": ["Guadalajara", "México"],
  "monterrey": ["Monterrey", "México"],
  "buenos aires": ["Buenos Aires", "Argentina"],
  "cordoba": ["Córdoba", "Argentina"],
  "córdoba": ["Córdoba", "Argentina"],
  "rosario": ["Rosario", "Argentina"],
  "bogota": ["Bogotá", "Colombia"],
  "bogotá": ["Bogotá", "Colombia"],
  "medellin": ["Medellín", "Colombia"],
  "medellín": ["Medellín", "Colombia"],
  "cali": ["Cali", "Colombia"],
  "lima": ["Lima", "Perú"],
  "arequipa": ["Arequipa", "Perú"],
  "santiago": ["Santiago de Chile", "Chile"],
  "santiago de chile": ["Santiago de Chile", "Chile"],
  "valparaiso": ["Valparaíso", "Chile"],
  "valparaíso": ["Valparaíso", "Chile"],
  "montevideo": ["Montevideo", "Uruguay"],
  "asuncion": ["Asunción", "Paraguay"],
  "asunción": ["Asunción", "Paraguay"],
  "la paz": ["La Paz", "Bolivia"],
  "santa cruz": ["Santa Cruz", "Bolivia"],
  "quito": ["Quito", "Ecuador"],
  "guayaquil": ["Guayaquil", "Ecuador"],
  "caracas": ["Caracas", "Venezuela"],
  "maracaibo": ["Maracaibo", "Venezuela"],
  "santo domingo": ["Santo Domingo", "República Dominicana"],
  "san juan": ["San Juan", "Puerto Rico"],
  "san jose": ["San José", "Costa Rica"],
  "san josé": ["San José", "Costa Rica"],
  "panama": ["Ciudad de Panamá", "Panamá"],
  "panamá": ["Ciudad de Panamá", "Panamá"],
  "tegucigalpa": ["Tegucigalpa", "Honduras"],
  "managua": ["Managua", "Nicaragua"],
  "san salvador": ["San Salvador", "El Salvador"],
  "guatemala": ["Ciudad de Guatemala", "Guatemala"],
  "brasilia": ["Brasilia", "Brasil"],
  "brasília": ["Brasilia", "Brasil"],
  "sao paulo": ["São Paulo", "Brasil"],
  "são paulo": ["São Paulo", "Brasil"],
  "rio de janeiro": ["Río de Janeiro", "Brasil"],
  "salvador de bahia": ["Salvador de Bahía", "Brasil"],
  "salvador de bahía": ["Salvador de Bahía", "Brasil"],
  "nueva york": ["Nueva York", "Estados Unidos"],
  "new york": ["Nueva York", "Estados Unidos"],
  "nyc": ["Nueva York", "Estados Unidos"],
  "washington": ["Washington D. C.", "Estados Unidos"],
  "los angeles": ["Los Ángeles", "Estados Unidos"],
  "los ángeles": ["Los Ángeles", "Estados Unidos"],
  "chicago": ["Chicago", "Estados Unidos"],
  "miami": ["Miami", "Estados Unidos"],
  "boston": ["Boston", "Estados Unidos"],
  "toronto": ["Toronto", "Canadá"],
  "ottawa": ["Ottawa", "Canadá"],
  "montreal": ["Montreal", "Canadá"],
  "montréal": ["Montreal", "Canadá"],
  "vancouver": ["Vancouver", "Canadá"],
  "el cairo": ["El Cairo", "Egipto"],
  "casablanca": ["Casablanca", "Marruecos"],
  "rabat": ["Rabat", "Marruecos"],
  "tunez": ["Túnez", "Túnez"],
  "túnez": ["Túnez", "Túnez"],
  "argel": ["Argel", "Argelia"],
  "nairobi": ["Nairobi", "Kenia"],
  "lagos": ["Lagos", "Nigeria"],
  "abuja": ["Abuya", "Nigeria"],
  "johannesburgo": ["Johannesburgo", "Sudáfrica"],
  "ciudad del cabo": ["Ciudad del Cabo", "Sudáfrica"],
  "tokio": ["Tokio", "Japón"],
  "osaka": ["Osaka", "Japón"],
  "seul": ["Seúl", "Corea del Sur"],
  "seúl": ["Seúl", "Corea del Sur"],
  "pekin": ["Pekín", "China"],
  "pekín": ["Pekín", "China"],
  "beijing": ["Pekín", "China"],
  "shanghai": ["Shanghái", "China"],
  "hong kong": ["Hong Kong", "China"],
  "singapur": ["Singapur", "Singapur"],
  "bangkok": ["Bangkok", "Tailandia"],
  "yakarta": ["Yakarta", "Indonesia"],
  "manila": ["Manila", "Filipinas"],
  "nueva delhi": ["Nueva Delhi", "India"],
  "mumbai": ["Mumbai", "India"],
  "bombay": ["Mumbai", "India"],
  "sidney": ["Sídney", "Australia"],
  "sydney": ["Sídney", "Australia"],
  "melbourne": ["Melbourne", "Australia"],
  "canberra": ["Canberra", "Australia"],
  "auckland": ["Auckland", "Nueva Zelanda"],
  "wellington": ["Wellington", "Nueva Zelanda"],
};

const COUNTRY_ALIASES = {
  "españa": "España",
  "espana": "España",
  "francia": "Francia",
  "reino unido": "Reino Unido",
  "alemania": "Alemania",
  "italia": "Italia",
  "portugal": "Portugal",
  "belgica": "Bélgica",
  "bélgica": "Bélgica",
  "paises bajos": "Países Bajos",
  "países bajos": "Países Bajos",
  "austria": "Austria",
  "suiza": "Suiza",
  "suecia": "Suecia",
  "noruega": "Noruega",
  "dinamarca": "Dinamarca",
  "finlandia": "Finlandia",
  "irlanda": "Irlanda",
  "polonia": "Polonia",
  "chequia": "Chequia",
  "hungria": "Hungría",
  "hungría": "Hungría",
  "grecia": "Grecia",
  "rumania": "Rumanía",
  "rumanía": "Rumanía",
  "bulgaria": "Bulgaria",
  "croacia": "Croacia",
  "serbia": "Serbia",
  "rusia": "Rusia",
  "ucrania": "Ucrania",
  "cuba": "Cuba",
  "mexico": "México",
  "méxico": "México",
  "argentina": "Argentina",
  "colombia": "Colombia",
  "peru": "Perú",
  "perú": "Perú",
  "chile": "Chile",
  "uruguay": "Uruguay",
  "paraguay": "Paraguay",
  "bolivia": "Bolivia",
  "ecuador": "Ecuador",
  "venezuela": "Venezuela",
  "brasil": "Brasil",
  "república dominicana": "República Dominicana",
  "republica dominicana": "República Dominicana",
  "costa rica": "Costa Rica",
  "panama": "Panamá",
  "panamá": "Panamá",
  "honduras": "Honduras",
  "nicaragua": "Nicaragua",
  "el salvador": "El Salvador",
  "guatemala": "Guatemala",
  "estados unidos": "Estados Unidos",
  "eeuu": "Estados Unidos",
  "usa": "Estados Unidos",
  "canada": "Canadá",
  "canadá": "Canadá",
  "egipto": "Egipto",
  "marruecos": "Marruecos",
  "tunez": "Túnez",
  "túnez": "Túnez",
  "argelia": "Argelia",
  "kenia": "Kenia",
  "nigeria": "Nigeria",
  "sudafrica": "Sudáfrica",
  "sudáfrica": "Sudáfrica",
  "japon": "Japón",
  "japón": "Japón",
  "corea del sur": "Corea del Sur",
  "china": "China",
  "singapur": "Singapur",
  "tailandia": "Tailandia",
  "indonesia": "Indonesia",
  "filipinas": "Filipinas",
  "india": "India",
  "australia": "Australia",
  "nueva zelanda": "Nueva Zelanda",
};

const COUNTRY_SOURCES = {
  "España": [["INE – Instituto Nacional de Estadística", "https://www.ine.es"], ["CIS – Centro de Investigaciones Sociológicas", "https://www.cis.es"], ["Datos.gob.es", "https://datos.gob.es"]],
  "Francia": [["INSEE – Institut national de la statistique", "https://www.insee.fr"], ["data.gouv.fr – Datos abiertos de Francia", "https://www.data.gouv.fr"], ["Santé publique France", "https://www.santepubliquefrance.fr"]],
  "Reino Unido": [["Office for National Statistics", "https://www.ons.gov.uk"], ["data.gov.uk", "https://www.data.gov.uk"], ["NHS Digital", "https://digital.nhs.uk"]],
  "Alemania": [["Destatis – Federal Statistical Office", "https://www.destatis.de"], ["GovData Germany", "https://www.govdata.de"], ["Robert Koch Institute", "https://www.rki.de"]],
  "Italia": [["ISTAT", "https://www.istat.it"], ["dati.gov.it", "https://www.dati.gov.it"], ["Ministero della Salute", "https://www.salute.gov.it"]],
  "Portugal": [["INE Portugal", "https://www.ine.pt"], ["dados.gov.pt", "https://dados.gov.pt"], ["SNS Portugal", "https://www.sns.gov.pt"]],
  "Cuba": [["ONEI – Oficina Nacional de Estadística e Información", "https://www.onei.gob.cu/"], ["Ministerio de Salud Pública de Cuba", "https://salud.msp.gob.cu/"], ["CEPALSTAT", "https://statistics.cepal.org/portal/cepalstat/"], ["Banco Mundial – Cuba", "https://data.worldbank.org/country/cuba"], ["UNData", "https://data.un.org/"]],
  "México": [["INEGI", "https://www.inegi.org.mx"], ["datos.gob.mx", "https://datos.gob.mx"], ["Secretaría de Salud", "https://www.gob.mx/salud"]],
  "Argentina": [["INDEC", "https://www.indec.gob.ar"], ["Datos Argentina", "https://datos.gob.ar"], ["Ministerio de Salud", "https://www.argentina.gob.ar/salud"]],
  "Colombia": [["DANE", "https://www.dane.gov.co"], ["Datos Abiertos Colombia", "https://www.datos.gov.co"], ["Ministerio de Salud y Protección Social", "https://www.minsalud.gov.co"]],
  "Perú": [["INEI", "https://www.inei.gob.pe"], ["Datos Abiertos Perú", "https://www.datosabiertos.gob.pe"], ["Ministerio de Salud", "https://www.gob.pe/minsa"]],
  "Chile": [["INE Chile", "https://www.ine.gob.cl"], ["Datos.gob.cl", "https://datos.gob.cl"], ["Ministerio de Salud", "https://www.minsal.cl"]],
  "Brasil": [["IBGE", "https://www.ibge.gov.br"], ["dados.gov.br", "https://dados.gov.br"], ["DATASUS", "https://datasus.saude.gov.br"]],
  "Estados Unidos": [["U.S. Census Bureau", "https://www.census.gov"], ["Data.gov", "https://data.gov"], ["CDC Data & Statistics", "https://www.cdc.gov/datastatistics/"], ["Bureau of Labor Statistics", "https://www.bls.gov"]],
  "Canadá": [["Statistics Canada", "https://www.statcan.gc.ca"], ["Open Government Canada", "https://open.canada.ca"], ["Public Health Agency of Canada", "https://www.canada.ca/en/public-health.html"]],
  "Australia": [["Australian Bureau of Statistics", "https://www.abs.gov.au"], ["data.gov.au", "https://data.gov.au"], ["Australian Institute of Health and Welfare", "https://www.aihw.gov.au"]],
  "Japón": [["Statistics Bureau of Japan", "https://www.stat.go.jp/english/"], ["e-Stat Japan", "https://www.e-stat.go.jp/en"], ["Ministry of Health, Labour and Welfare", "https://www.mhlw.go.jp/english/"]],
  "China": [["National Bureau of Statistics of China", "https://www.stats.gov.cn/english/"], ["National Health Commission", "http://en.nhc.gov.cn/"]],
  "India": [["MOSPI India", "https://www.mospi.gov.in"], ["data.gov.in", "https://data.gov.in"], ["Ministry of Health and Family Welfare", "https://mohfw.gov.in"]],
  "Sudáfrica": [["Statistics South Africa", "https://www.statssa.gov.za"], ["DataFirst", "https://www.datafirst.uct.ac.za"], ["Department of Health", "https://www.health.gov.za"]],
};

const CITY_SOURCES = {
  "Madrid": [["Ayuntamiento de Madrid – Datos Abiertos", "https://datos.madrid.es"], ["Comunidad de Madrid – Datos Abiertos", "https://datos.comunidad.madrid/"]],
  "Barcelona": [["Open Data BCN", "https://opendata-ajuntament.barcelona.cat/"], ["IDESCAT", "https://www.idescat.cat"]],
  "Valencia": [["València Open Data", "https://valencia.opendatasoft.com/"], ["Generalitat Valenciana – Portal Estadístico", "https://pegv.gva.es/es/estadistica"]],
  "Sevilla": [["Ayuntamiento de Sevilla – Datos Abiertos", "https://www.sevilla.org/servicios/participacion-ciudadana/datos-abiertos"], ["IECA Andalucía", "https://www.juntadeandalucia.es/institutodeestadisticaycartografia/"]],
  "Zaragoza": [["Ayuntamiento de Zaragoza – Datos Abiertos", "https://www.zaragoza.es/sede/portal/datos-abiertos/"], ["IAEST", "https://www.aragon.es/iaest"]],
  "París": [["Paris Data", "https://opendata.paris.fr/"], ["INSEE – Île-de-France", "https://www.insee.fr/fr/statistiques?debut=0&theme=1&geo=REG-11"]],
  "Nueva York": [["NYC Open Data", "https://opendata.cityofnewyork.us/"], ["NYC Health Data", "https://www.nyc.gov/site/doh/data/data-publications.page"], ["NY State Open Data", "https://data.ny.gov/"]],
  "Buenos Aires": [["Buenos Aires Data", "https://data.buenosaires.gob.ar/"], ["Estadística y Censos CABA", "https://www.estadisticaciudad.gob.ar/eyc/"]],
  "Ciudad de México": [["Portal de Datos Abiertos CDMX", "https://datos.cdmx.gob.mx/"], ["INEGI CDMX", "https://www.inegi.org.mx"]],
  "Bogotá": [["Datos Abiertos Bogotá", "https://datosabiertos.bogota.gov.co/"], ["DANE", "https://www.dane.gov.co"]],
  "Lima": [["Plataforma Nacional de Datos Abiertos Perú", "https://www.datosabiertos.gob.pe/"], ["INEI", "https://www.inei.gob.pe"]],
  "Santiago de Chile": [["Datos.gob.cl", "https://datos.gob.cl"], ["INE Chile", "https://www.ine.gob.cl"]],
  "São Paulo": [["Prefeitura de São Paulo – Dados Abertos", "https://dados.prefeitura.sp.gov.br/"], ["IBGE", "https://www.ibge.gov.br"]],
};
const SK_DOMINIOS = [
  { keys: ["digital", "algorit", "tiktok", "internet", "redes sociales", "plataforma", "brecha digital"], macro: "ecosistema digital / economía de plataformas", meso: "algoritmos, comunidades online y cámaras de eco", micro: "consumo cotidiano de contenidos e identidad digital" },
  { keys: ["política", "politica", "voto", "partido", "radicalización", "radicalizacion", "hegemon"], macro: "campo político, polarización y legitimidad", meso: "discursos, organizaciones y redes de movilización", micro: "identificación política y percepción de amenaza" },
  { keys: ["juventud", "juvenil", "jóvenes", "jovenes", "adolesc"], macro: "estructura generacional y oportunidades vitales", meso: "grupos de pares, escuela y redes juveniles", micro: "trayectorias biográficas e identidad juvenil" },
  { keys: ["educación", "educacion", "instrucción", "instruccion", "educativo", "escuela", "capital cultural", "fracaso escolar"], macro: "sistema educativo y desigualdad de credenciales", meso: "centros, expectativas docentes y capital cultural familiar", micro: "trayectorias escolares y expectativas de futuro" },
  { keys: ["trabajo", "empleo", "laboral", "paro", "desempleo", "salario", "precar"], macro: "mercado laboral y estructura ocupacional", meso: "segmentación, contratos y redes de acceso al empleo", micro: "empleabilidad percibida y estrategias laborales" },
  { keys: ["género", "genero", "mujer", "mujeres", "hombres", "varones", "masculinidad", "machismo", "patriarc"], macro: "orden de género y división social del poder", meso: "normas institucionales, familia y pares generizados", micro: "identidades de género y reconocimiento cotidiano" },
  { keys: ["familia", "hogar", "padres", "madres", "familiar"], macro: "régimen familiar y reproducción social", meso: "hogares, cuidados y autoridad parental", micro: "vínculos afectivos y negociación doméstica" },
  { keys: ["salud mental", "ansiedad", "depresión", "depresion", "bienestar psicológico", "bienestar psicologico"], macro: "régimen de salud mental y vulnerabilidad social", meso: "servicios, apoyos comunitarios y redes de cuidado", micro: "malestar subjetivo y estrategias de afrontamiento" },
  { keys: ["salud", "enfermedad", "sanitario", "hospital"], macro: "sistema sanitario y desigualdades en salud", meso: "servicios, accesibilidad y redes de apoyo", micro: "experiencias corporales y prácticas de cuidado" },
  { keys: ["pobreza", "exclusión", "exclusion", "renta", "ingresos", "vulnerabilidad"], macro: "estructura de desigualdad y distribución de recursos", meso: "servicios sociales, barrios y redes de apoyo", micro: "estrategias de supervivencia y privación cotidiana" },
  { keys: ["cultura", "representaciones", "valores", "símbol", "simbol", "consumo cultural"], macro: "campo cultural y jerarquías simbólicas", meso: "instituciones culturales, medios y comunidades interpretativas", micro: "gustos, disposiciones y prácticas de sentido" },
  { keys: ["emociones", "afectos", "miedo", "ira", "odio", "resentimiento", "esperanza"], macro: "régimen afectivo y clima emocional colectivo", meso: "rituales, grupos y circulación de afectos", micro: "experiencia emocional y orientación práctica" },
  { keys: ["conocimiento", "sentido común", "sentido comun", "normalidad", "cognitivo", "epistem"], macro: "régimen de verdad y producción social del conocimiento", meso: "instituciones expertas, medios y autoridad epistémica", micro: "juicios, creencias y esquemas de interpretación" },
  { keys: ["urbana", "barrio", "vecindario", "gentrificación", "gentrificacion", "segregación territorial", "segregacion territorial", "periferia"], macro: "estructura urbana y desigualdad territorial", meso: "barrios, equipamientos y redes vecinales", micro: "usos del espacio y pertenencia territorial" },
  { keys: ["migración", "migracion", "migrante", "inmigración", "inmigracion", "racismo", "xenofobia"], macro: "régimen migratorio y fronteras sociales", meso: "redes transnacionales, instituciones y discriminación", micro: "trayectorias migrantes e identificación cotidiana" },
  { keys: ["religión", "religion", "iglesia", "creencia", "secular"], macro: "campo religioso y secularización", meso: "comunidades religiosas y autoridad moral", micro: "creencias, prácticas rituales y sentido vital" },
  { keys: ["delincuencia", "delito", "crimen", "desviación", "desviacion", "control social"], macro: "control social, ley y desigualdad penal", meso: "policía, escuela, calle y redes de desviación", micro: "etiquetamiento, decisiones situadas y justificaciones" },
  { keys: ["consumo", "mercado", "publicidad", "marca", "cliente"], macro: "capitalismo de consumo y producción de necesidades", meso: "mercados, publicidad y grupos de referencia", micro: "deseos, estilos de vida y prácticas de compra" },
  { keys: ["medio ambiente", "ambiental", "ecología", "ecologia", "clima", "sostenibilidad"], macro: "crisis ecosocial y régimen ambiental", meso: "políticas ambientales, territorio y conflictos locales", micro: "percepción del riesgo y prácticas ecológicas" },
  { keys: ["rural", "campo", "agrario", "despoblación", "despoblacion"], macro: "estructura rural y desigualdad centro-periferia", meso: "comunidad local, servicios y economía agraria", micro: "arraigo, movilidad y estrategias familiares" },
  { keys: ["envejecimiento", "mayores", "vejez", "ancianos", "dependencia"], macro: "régimen demográfico y sistema de cuidados", meso: "familias, residencias y servicios sociosanitarios", micro: "autonomía, soledad y experiencia de la edad" },
  { keys: ["discapacidad", "diversidad funcional", "accesibilidad"], macro: "régimen de capacidad y desigualdad estructural", meso: "instituciones, apoyos y barreras de accesibilidad", micro: "autonomía, reconocimiento y vida cotidiana" },
  { keys: ["organización", "organizacion", "empresa", "burocracia", "institucional"], macro: "estructura organizacional y racionalidad burocrática", meso: "normas internas, jerarquías y cultura organizacional", micro: "roles, decisiones y adaptación práctica" },
  { keys: ["ciencia", "tecnología", "tecnologia", "innovación", "innovacion", "ia", "inteligencia artificial"], macro: "régimen sociotécnico e innovación tecnológica", meso: "infraestructuras, expertos y mediaciones técnicas", micro: "apropiación, confianza y usos situados" },
];
